# Generated by Django 2.2.10 on 2020-02-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('icao', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.SmallIntegerField()),
                ('timezone', models.CharField(max_length=40)),
            ],
        ),
    ]
