# Generated by Django 2.2.10 on 2020-02-15 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flightapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sovereignty', models.CharField(max_length=32)),
                ('admin', models.CharField(max_length=35)),
                ('continent', models.CharField(max_length=23)),
                ('min_longitude', models.FloatField()),
                ('max_longitude', models.FloatField()),
                ('min_latitude', models.FloatField()),
                ('max_latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ShapePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapi.MapShape')),
            ],
        ),
        migrations.CreateModel(
            name='MapPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.PositiveIntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapi.MapShape')),
            ],
        ),
    ]
