# Generated by Django 2.2.10 on 2020-03-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapi', '0003_auto_20200304_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shapepart',
            name='shape',
        ),
        migrations.DeleteModel(
            name='MapPoint',
        ),
        migrations.DeleteModel(
            name='MapShape',
        ),
        migrations.DeleteModel(
            name='ShapePart',
        ),
    ]
