# Generated by Django 2.2.10 on 2020-03-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapi', '0005_mappoint_mapshape_shapepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapepart',
            name='max_latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shapepart',
            name='max_longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shapepart',
            name='min_latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shapepart',
            name='min_longitude',
            field=models.FloatField(default=0),
        ),
    ]
